added conditional jobs

diff --git a/.github/workflows/container-local-test.yml b/.github/workflows/container-local-test.yml
--- a/.github/workflows/container-local-test.yml
+++ b/.github/workflows/container-local-test.yml
@@ -54,4 +54,9 @@ jobs:
           docker image ls -a
           docker run ${{ env.IMAGE_NAME }} version
           docker run -v "$(pwd)":"/scanoss" ${{ env.IMAGE_NAME }} scan -o results.json tests
-          echo "ID Count: $(cat results.json | grep '"id":' | wc -l)"
+          id_count=$(cat results.json | grep '"id":' | wc -l)
+          echo "ID Count: $id_count"
+          if [[ $id_count -lt 1 ]]; then
+            echo "Error: Scan test did not produce any results. Failing"
+            exit 1
+          fi
diff --git a/.github/workflows/python-local-test.yml b/.github/workflows/python-local-test.yml
--- a/.github/workflows/python-local-test.yml
+++ b/.github/workflows/python-local-test.yml
@@ -18,30 +18,35 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v3
+      - uses: actions/checkout@v3
 
-    - name: Set up Python
-      uses: actions/setup-python@v3
-      with:
-        python-version: '3.10.x'
+      - name: Set up Python
+        uses: actions/setup-python@v3
+        with:
+          python-version: '3.10.x'
 
-    - name: Install Dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements-dev.txt
+      - name: Install Dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements-dev.txt
 
-    - name: Build Local Package
-      run: make dist
+      - name: Build Local Package
+        run: make dist
 
-    - name: Install Test Package
-      run: |
-        pip install -r requirements.txt
-        pip install dist/scanoss-*-py3-none-any.whl
-        which scanoss-py
+      - name: Install Test Package
+        run: |
+          pip install -r requirements.txt
+          pip install dist/scanoss-*-py3-none-any.whl
+          which scanoss-py
 
-    - name: Run Tests
-      run: |
-        which scanoss-py
-        scanoss-py version
-        scanoss-py scan tests > results.json
-        echo "ID Count: $(cat results.json | grep '"id":' | wc -l)"
+      - name: Run Tests
+        run: |
+          which scanoss-py
+          scanoss-py version
+          scanoss-py scan tests > results.json
+          id_count=$(cat results.json | grep '"id":' | wc -l)
+          echo "ID Count: $id_count"
+          if [[ $id_count -lt 1 ]]; then
+            echo "Error: Scan test did not produce any results. Failing"
+            exit 1
+          fi
diff --git a/.github/workflows/python-publish-testpypi.yml b/.github/workflows/python-publish-testpypi.yml
--- a/.github/workflows/python-publish-testpypi.yml
+++ b/.github/workflows/python-publish-testpypi.yml
@@ -1,7 +1,7 @@
 name: Publish Python Package - TestPyPI
 # This workflow will upload a TestPyPI Python Package using Twine on demand (dispatch)
 
-on: [workflow_dispatch]
+on: [ workflow_dispatch ]
 
 permissions:
   contents: read
@@ -11,62 +11,70 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v3
+      - uses: actions/checkout@v3
 
-    - name: Set up Python
-      uses: actions/setup-python@v3
-      with:
-        python-version: '3.10.x'
+      - name: Set up Python
+        uses: actions/setup-python@v3
+        with:
+          python-version: '3.10.x'
 
-    - name: Install Dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements-dev.txt
+      - name: Install Dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements-dev.txt
 
-    - name: Build Package
-      run: make dist
+      - name: Build Package
+        run: make dist
 
-    - name: Install Test Package
-      run: |
-        pip install -r requirements.txt
-        pip install dist/scanoss-*-py3-none-any.whl
-        which scanoss-py
+      - name: Install Test Package
+        run: |
+          pip install -r requirements.txt
+          pip install dist/scanoss-*-py3-none-any.whl
+          which scanoss-py
 
-    - name: Run Local Tests
-      run: |
-        which scanoss-py
-        scanoss-py version
-        scanoss-py scan tests > results.json
-        echo "ID Count: $(cat results.json | grep '"id":' | wc -l)"
-        pip uninstall scanoss
+      - name: Run Local Tests
+        run: |
+          which scanoss-py
+          scanoss-py version
+          scanoss-py scan tests > results.json
+          echo "ID Count: $(cat results.json | grep '"id":' | wc -l)"
+          pip uninstall -y scanoss
 
-    - name: Publish Test Package
-      uses: pypa/gh-action-pypi-publish@release/v1
-      with:
-        user: __token__
-        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
-        repository_url: https://test.pypi.org/legacy/
+      - name: Publish Test Package
+        id: publish-testpypi-package
+        uses: pypa/gh-action-pypi-publish@release/v1
+        with:
+          user: __token__
+          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
+          repository_url: https://test.pypi.org/legacy/
 
   test:
+    if: success()
+    needs: [ publish-testpypi-package ]
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v3
+      - uses: actions/checkout@v3
 
-    - name: Set up Python
-      uses: actions/setup-python@v3
-      with:
-        python-version: '3.10.x'
+      - name: Set up Python
+        uses: actions/setup-python@v3
+        with:
+          python-version: '3.10.x'
 
-    - name: Install Remote Package
-      run: |
-        pip install -r requirements.txt
-        pip install -i https://test.pypi.org/simple/ --upgrade scanoss
-        which scanoss-py
+      - name: Install Remote Package
+        run: |
+          pip install -r requirements.txt
+          pip install -i https://test.pypi.org/simple/ --upgrade scanoss
+          which scanoss-py
 
-    - name: Run Tests
-      run: |
-        which scanoss-py
-        scanoss-py version
-        scanoss-py scan tests > results.json
-        echo "ID Count: $(cat results.json | grep '"id":' | wc -l)"
+      - name: Run Tests
+        run: |
+          which scanoss-py
+          scanoss-py version
+          scanoss-py scan tests > results.json
+          id_count=$(cat results.json | grep '"id":' | wc -l)
+          echo "ID Count: $id_count"
+          if [[ $id_count -lt 1 ]]; then
+            echo "Error: Scan test did not produce any results. Failing"
+            exit 1
+          fi
