fixed job dependency

diff --git a/.github/workflows/container-publish-ghcr.yml b/.github/workflows/container-publish-ghcr.yml
--- a/.github/workflows/container-publish-ghcr.yml
+++ b/.github/workflows/container-publish-ghcr.yml
@@ -25,35 +25,27 @@ jobs:
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v3
-        
+
       # Setup and build python package
       - name: Set up Python
         uses: actions/setup-python@v3
         with:
           python-version: '3.10.x'
-          
+
       - name: Install Dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements-dev.txt
-          
+
       - name: Build package
         run: make dist
-        
-      # Install the cosign tool except on PR
-#      - name: Install cosign
-#        if: github.event_name != 'pull_request'
-#        uses: sigstore/cosign-installer@v2
-#
-#      - name: Check Cosign Version
-#        run: cosign version
 
         # Add support for more platforms with QEMU
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v2
 
       # Workaround: https://github.com/docker/build-push-action/issues/461
-#        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
+      #        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
       - name: Setup Docker buildx
         uses: docker/setup-buildx-action@v2
 
@@ -92,8 +84,21 @@ jobs:
           docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
           docker run ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} version
           docker run ${{ env.IMAGE_NAME }} scan -o results.json tests
-          echo "ID Count: $(cat results.json | grep '"id":' | wc -l)"
+          id_count=$(cat results.json | grep '"id":' | wc -l)
+          echo "ID Count: $id_count"
+          if [[ $id_count -lt 1 ]]; then
+            echo "Error: Scan test did not produce any results. Failing"
+            exit 1
+          fi
 
+# Install the cosign tool except on PR
+#      - name: Install cosign
+#        if: github.event_name != 'pull_request'
+#        uses: sigstore/cosign-installer@v2
+#
+#      - name: Check Cosign Version
+#        run: cosign version
+#
 #      - name: Sign Docker Image
 #        if: ${{ github.event_name != 'pull_request' }}
 #        env:
