added scan and wfp filter options

diff --git a/.github/workflows/python-local-test.yml b/.github/workflows/python-local-test.yml
--- a/.github/workflows/python-local-test.yml
+++ b/.github/workflows/python-local-test.yml
@@ -64,3 +64,17 @@ jobs:
             echo "Error: Scan test did not produce any results. Failing"
             exit 1
           fi
+
+      - name: Run Tests HPSM (fast winnowing)
+        run: |
+          pip install scanoss_winnowing
+          which scanoss-py
+          scanoss-py version
+          scanoss-py utils fast
+          scanoss-py scan -H tests > results.json
+          id_count=$(cat results.json | grep '"id":' | wc -l)
+          echo "ID Count: $id_count"
+          if [[ $id_count -lt 1 ]]; then
+            echo "Error: Scan test did not produce any results. Failing"
+            exit 1
+          fi
