added fast winnowing module integration

diff --git a/.github/workflows/python-local-test.yml b/.github/workflows/python-local-test.yml
--- a/.github/workflows/python-local-test.yml
+++ b/.github/workflows/python-local-test.yml
@@ -16,7 +16,6 @@ permissions:
 jobs:
   build:
     runs-on: ubuntu-latest
-
     steps:
       - uses: actions/checkout@v3
 
@@ -43,6 +42,21 @@ jobs:
         run: |
           which scanoss-py
           scanoss-py version
+          scanoss-py fast
+          scanoss-py scan tests > results.json
+          id_count=$(cat results.json | grep '"id":' | wc -l)
+          echo "ID Count: $id_count"
+          if [[ $id_count -lt 1 ]]; then
+            echo "Error: Scan test did not produce any results. Failing"
+            exit 1
+          fi
+
+      - name: Run Tests (fast winnowing)
+        run: |
+          pip install scanoss_winnowing
+          which scanoss-py
+          scanoss-py version
+          scanoss-py fast
           scanoss-py scan tests > results.json
           id_count=$(cat results.json | grep '"id":' | wc -l)
           echo "ID Count: $id_count"
diff --git a/.github/workflows/python-publish-testpypi.yml b/.github/workflows/python-publish-testpypi.yml
--- a/.github/workflows/python-publish-testpypi.yml
+++ b/.github/workflows/python-publish-testpypi.yml
@@ -9,7 +9,6 @@ permissions:
 jobs:
   deploy:
     runs-on: ubuntu-latest
-
     steps:
       - uses: actions/checkout@v3
 
@@ -39,12 +38,18 @@ jobs:
           which scanoss-py
           scanoss-py version
           scanoss-py scan tests > results.json
-          echo "ID Count: $(cat results.json | grep '"id":' | wc -l)"
+          id_count=$(cat results.json | grep '"id":' | wc -l)
+          echo "ID Count: $id_count"
+          if [[ $id_count -lt 1 ]]; then
+            echo "Error: Scan test did not produce any results. Failing"
+            exit 1
+          fi
           pip uninstall -y scanoss
 
       - name: Publish Test Package
         uses: pypa/gh-action-pypi-publish@release/v1
         with:
+          skip_existing: true
           user: __token__
           password: ${{ secrets.TEST_PYPI_API_TOKEN }}
           repository_url: https://test.pypi.org/legacy/
@@ -74,6 +79,21 @@ jobs:
         run: |
           which scanoss-py
           scanoss-py version
+          scanoss-py fast
+          scanoss-py scan tests > results.json
+          id_count=$(cat results.json | grep '"id":' | wc -l)
+          echo "ID Count: $id_count"
+          if [[ $id_count -lt 1 ]]; then
+            echo "Error: Scan test did not produce any results. Failing"
+            exit 1
+          fi
+
+      - name: Run Tests (fast winnowing)
+        run: |
+          pip install scanoss_winnowing
+          which scanoss-py
+          scanoss-py version
+          scanoss-py fast
           scanoss-py scan tests > results.json
           id_count=$(cat results.json | grep '"id":' | wc -l)
           echo "ID Count: $id_count"
