Feature/mscasso/sp 3430 add line headers filter (#172)
* Add file headers filter feature.

* Add HeaderFilter class.

* Add --skip-headers and --skip-headers-limit flags.

* Update unit tests and workflows.

* Update CHANGELOG.
---------

Co-authored-by: eeisegn <eeisegn@gmail.com>

diff --git a/.github/workflows/python-local-test.yml b/.github/workflows/python-local-test.yml
--- a/.github/workflows/python-local-test.yml
+++ b/.github/workflows/python-local-test.yml
@@ -60,6 +60,13 @@ jobs:
             echo "Error: Scan test did not produce any results. Failing"
             exit 1
           fi
+          scanoss-py wfp --skip-headers tests > fingers.wfp
+          wfp_count=$(cat fingers.wfp | grep 'file=' | wc -l)
+          echo "WFP Count: $wfp_count"
+          if [[ $wfp_count -lt 1 ]]; then
+            echo "Error: WFP test did not produce any results. Failing"
+            exit 1
+          fi
 
       - name: Run Tests (fast winnowing)
         run: |
@@ -74,7 +81,13 @@ jobs:
             echo "Error: Scan test did not produce any results. Failing"
             exit 1
           fi
-      
+          scanoss-py wfp --skip-headers tests > fingers.wfp
+          wfp_count=$(cat fingers.wfp | grep 'file=' | wc -l)
+          echo "WFP Count: $wfp_count"
+          if [[ $wfp_count -lt 1 ]]; then
+            echo "Error: WFP test did not produce any results. Failing"
+            exit 1
+          fi
 
       - name: Run Tests HPSM (fast winnowing)
         run: |
@@ -89,7 +102,6 @@ jobs:
             echo "Error: WFP test did not produce any results. Failing"
             exit 1
           fi
-      
 
       - name: Run Unit Tests
         run: |
diff --git a/.github/workflows/python-publish-pypi.yml b/.github/workflows/python-publish-pypi.yml
--- a/.github/workflows/python-publish-pypi.yml
+++ b/.github/workflows/python-publish-pypi.yml
@@ -35,6 +35,10 @@ jobs:
           pip install dist/scanoss-*-py3-none-any.whl
           which scanoss-py
 
+      - name: Run Unit Tests
+        run: |
+          make unit_test
+
       - name: Run Local Tests
         run: |
           which scanoss-py
@@ -45,6 +49,13 @@ jobs:
           echo "ID Count: $id_count"
           if [[ $id_count -lt 1 ]]; then
             echo "Error: Scan test did not produce any results. Failing"
+            exit 1
+          fi
+          scanoss-py wfp --skip-headers tests > fingers.wfp
+          wfp_count=$(cat fingers.wfp | grep 'file=' | wc -l)
+          echo "WFP Count: $wfp_count"
+          if [[ $wfp_count -lt 1 ]]; then
+            echo "Error: WFP test did not produce any results. Failing"
             exit 1
           fi
           pip uninstall -y scanoss
@@ -102,6 +113,13 @@ jobs:
             echo "Error: Scan test did not produce any results. Failing"
             exit 1
           fi
+          scanoss-py wfp --skip-headers tests > fingers.wfp
+          wfp_count=$(cat fingers.wfp | grep 'file=' | wc -l)
+          echo "WFP Count: $wfp_count"
+          if [[ $wfp_count -lt 1 ]]; then
+            echo "Error: WFP test did not produce any results. Failing"
+            exit 1
+          fi
 
       - name: Run Tests (fast winnowing)
         run: |
@@ -114,6 +132,13 @@ jobs:
           echo "ID Count: $id_count"
           if [[ $id_count -lt 1 ]]; then
             echo "Error: Scan test did not produce any results. Failing"
+            exit 1
+          fi
+          scanoss-py wfp --skip-headers tests > fingers.wfp
+          wfp_count=$(cat fingers.wfp | grep 'file=' | wc -l)
+          echo "WFP Count: $wfp_count"
+          if [[ $wfp_count -lt 1 ]]; then
+            echo "Error: WFP test did not produce any results. Failing"
             exit 1
           fi
 
